# Generated by Django 3.0.1 on 2020-02-04 12:41

from django.db import migrations, models
import lessons.models
import studious.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_review_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='review_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='review_incorrect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='review_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(max_length=200, storage=studious.storage_backends.LessonStorage(), upload_to=lessons.models.user_directory_path),
        ),
    ]
