# Generated by Django 3.0.1 on 2020-02-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200204_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_review_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
