# Generated by Django 3.0.1 on 2020-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200204_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='review_started',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
